# Form implementation generated from reading ui file 'Pass_Biom.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pass_Biom(object):
    def setupUi(self, Pass_Biom):
        Pass_Biom.setObjectName("Pass_Biom")
        Pass_Biom.resize(672, 600)
        Pass_Biom.setMinimumSize(QtCore.QSize(672, 600))
        Pass_Biom.setStyleSheet("background-color: rgb(32, 33, 37);")
        self.centralwidget = QtWidgets.QWidget(Pass_Biom)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_of_choice = QtWidgets.QFrame(self.main_frame)
        self.frame_of_choice.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_of_choice.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_of_choice.setObjectName("frame_of_choice")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_of_choice)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_addEdit = QtWidgets.QLabel(self.frame_of_choice)
        self.label_addEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.label_addEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_addEdit.setFont(font)
        self.label_addEdit.setStyleSheet("color: white;")
        self.label_addEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_addEdit.setObjectName("label_addEdit")
        self.horizontalLayout_5.addWidget(self.label_addEdit)
        self.comboBox_addEdit = QtWidgets.QComboBox(self.frame_of_choice)
        self.comboBox_addEdit.setMinimumSize(QtCore.QSize(468, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_addEdit.setFont(font)
        self.comboBox_addEdit.setStyleSheet("selection-background-color: white;\n"
"selection-color:rgb(21, 22, 26);\n"
"background-color: rgb(21, 22, 26);\n"
"color: rgb(190, 190, 190);\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"")
        self.comboBox_addEdit.setObjectName("comboBox_addEdit")
        self.comboBox_addEdit.addItem("")
        self.comboBox_addEdit.setItemText(0, "Додати")
        self.horizontalLayout_5.addWidget(self.comboBox_addEdit)
        self.verticalLayout_2.addWidget(self.frame_of_choice, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.top_frame = QtWidgets.QFrame(self.main_frame)
        self.top_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_Button = QtWidgets.QPushButton(self.top_frame)
        self.image_Button.setMinimumSize(QtCore.QSize(175, 175))
        self.image_Button.setMaximumSize(QtCore.QSize(175, 175))
        self.image_Button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.image_Button.setStyleSheet("border-bottom: 0px;\n"
"border-right: 0px;\n"
"border-top: 0px;\n"
"border-left: 0px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Add_image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.image_Button.setIcon(icon)
        self.image_Button.setIconSize(QtCore.QSize(175, 175))
        self.image_Button.setObjectName("image_Button")
        self.horizontalLayout.addWidget(self.image_Button)
        self.center_frame = QtWidgets.QFrame(self.top_frame)
        self.center_frame.setMinimumSize(QtCore.QSize(236, 0))
        self.center_frame.setObjectName("center_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.center_frame)
        self.verticalLayout_3.setContentsMargins(5, 0, -1, -1)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_lname = QtWidgets.QLabel(self.center_frame)
        self.label_lname.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_lname.setFont(font)
        self.label_lname.setMouseTracking(True)
        self.label_lname.setStyleSheet("color: white;")
        self.label_lname.setScaledContents(False)
        self.label_lname.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_lname.setObjectName("label_lname")
        self.verticalLayout_3.addWidget(self.label_lname)
        self.lineEdit_lname = QtWidgets.QLineEdit(self.center_frame)
        self.lineEdit_lname.setMinimumSize(QtCore.QSize(222, 29))
        self.lineEdit_lname.setMaximumSize(QtCore.QSize(222, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_lname.setFont(font)
        self.lineEdit_lname.setMouseTracking(False)
        self.lineEdit_lname.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_lname.setText("")
        self.lineEdit_lname.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_lname.setClearButtonEnabled(True)
        self.lineEdit_lname.setObjectName("lineEdit_lname")
        self.verticalLayout_3.addWidget(self.lineEdit_lname)
        self.label_mname = QtWidgets.QLabel(self.center_frame)
        self.label_mname.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_mname.setFont(font)
        self.label_mname.setMouseTracking(True)
        self.label_mname.setStyleSheet("color: white;")
        self.label_mname.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_mname.setObjectName("label_mname")
        self.verticalLayout_3.addWidget(self.label_mname)
        self.lineEdit_patronymic = QtWidgets.QLineEdit(self.center_frame)
        self.lineEdit_patronymic.setMinimumSize(QtCore.QSize(222, 30))
        self.lineEdit_patronymic.setMaximumSize(QtCore.QSize(222, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_patronymic.setFont(font)
        self.lineEdit_patronymic.setMouseTracking(False)
        self.lineEdit_patronymic.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_patronymic.setDragEnabled(False)
        self.lineEdit_patronymic.setReadOnly(False)
        self.lineEdit_patronymic.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_patronymic.setClearButtonEnabled(True)
        self.lineEdit_patronymic.setObjectName("lineEdit_patronymic")
        self.verticalLayout_3.addWidget(self.lineEdit_patronymic)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_note = QtWidgets.QLabel(self.center_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_note.setFont(font)
        self.label_note.setMouseTracking(True)
        self.label_note.setStyleSheet("color: white;")
        self.label_note.setObjectName("label_note")
        self.verticalLayout_3.addWidget(self.label_note, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addWidget(self.center_frame)
        self.right_frame = QtWidgets.QFrame(self.top_frame)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_4.setContentsMargins(5, 0, 0, 3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_fname = QtWidgets.QLabel(self.right_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_fname.setFont(font)
        self.label_fname.setMouseTracking(True)
        self.label_fname.setStyleSheet("color: white;")
        self.label_fname.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_fname.setObjectName("label_fname")
        self.verticalLayout_4.addWidget(self.label_fname)
        self.lineEdit_fname = QtWidgets.QLineEdit(self.right_frame)
        self.lineEdit_fname.setMinimumSize(QtCore.QSize(222, 30))
        self.lineEdit_fname.setMaximumSize(QtCore.QSize(222, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_fname.setFont(font)
        self.lineEdit_fname.setMouseTracking(False)
        self.lineEdit_fname.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_fname.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_fname.setClearButtonEnabled(True)
        self.lineEdit_fname.setObjectName("lineEdit_fname")
        self.verticalLayout_4.addWidget(self.lineEdit_fname)
        self.label_passport = QtWidgets.QLabel(self.right_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_passport.setFont(font)
        self.label_passport.setMouseTracking(True)
        self.label_passport.setStyleSheet("color: white;")
        self.label_passport.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_passport.setObjectName("label_passport")
        self.verticalLayout_4.addWidget(self.label_passport)
        self.lineEdit_passport = QtWidgets.QLineEdit(self.right_frame)
        self.lineEdit_passport.setMinimumSize(QtCore.QSize(222, 30))
        self.lineEdit_passport.setMaximumSize(QtCore.QSize(222, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_passport.setFont(font)
        self.lineEdit_passport.setMouseTracking(False)
        self.lineEdit_passport.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_passport.setDragEnabled(False)
        self.lineEdit_passport.setReadOnly(False)
        self.lineEdit_passport.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_passport.setClearButtonEnabled(True)
        self.lineEdit_passport.setObjectName("lineEdit_passport")
        self.verticalLayout_4.addWidget(self.lineEdit_passport)
        self.label_post = QtWidgets.QLabel(self.right_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_post.setFont(font)
        self.label_post.setMouseTracking(True)
        self.label_post.setStyleSheet("color: white;")
        self.label_post.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_post.setObjectName("label_post")
        self.verticalLayout_4.addWidget(self.label_post)
        self.lineEdit_post = QtWidgets.QLineEdit(self.right_frame)
        self.lineEdit_post.setMinimumSize(QtCore.QSize(222, 30))
        self.lineEdit_post.setMaximumSize(QtCore.QSize(222, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_post.setFont(font)
        self.lineEdit_post.setMouseTracking(False)
        self.lineEdit_post.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_post.setDragEnabled(False)
        self.lineEdit_post.setReadOnly(False)
        self.lineEdit_post.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_post.setClearButtonEnabled(True)
        self.lineEdit_post.setObjectName("lineEdit_post")
        self.verticalLayout_4.addWidget(self.lineEdit_post)
        self.horizontalLayout.addWidget(self.right_frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.top_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.middle_frame = QtWidgets.QFrame(self.main_frame)
        self.middle_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.middle_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_frame = QtWidgets.QFrame(self.middle_frame)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_13.setContentsMargins(5, 0, -1, -1)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_batchAdding = QtWidgets.QLabel(self.left_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        self.label_batchAdding.setFont(font)
        self.label_batchAdding.setMouseTracking(True)
        self.label_batchAdding.setStyleSheet("color: white;")
        self.label_batchAdding.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_batchAdding.setObjectName("label_batchAdding")
        self.verticalLayout_13.addWidget(self.label_batchAdding)
        self.listWidget = QtWidgets.QListWidget(self.left_frame)
        self.listWidget.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("selection-color: rgb(21, 22, 26);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.listWidget.setIconSize(QtCore.QSize(13, 13))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_13.addWidget(self.listWidget)
        self.horizontalLayout_4.addWidget(self.left_frame)
        self.lower_right_frame = QtWidgets.QFrame(self.middle_frame)
        self.lower_right_frame.setObjectName("lower_right_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.lower_right_frame)
        self.verticalLayout_14.setContentsMargins(5, 0, 0, 3)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(0, 26, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_14.addItem(spacerItem1)
        self.label_note_1 = QtWidgets.QLabel(self.lower_right_frame)
        self.label_note_1.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_note_1.setFont(font)
        self.label_note_1.setStyleSheet("color: white;")
        self.label_note_1.setWordWrap(True)
        self.label_note_1.setObjectName("label_note_1")
        self.verticalLayout_14.addWidget(self.label_note_1, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.lower_right_frame_2 = QtWidgets.QFrame(self.lower_right_frame)
        self.lower_right_frame_2.setObjectName("lower_right_frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.lower_right_frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_clear = QtWidgets.QPushButton(self.lower_right_frame_2)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 0, 3);\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(127, 38, 38, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(136, 0, 2);\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_3.addWidget(self.pushButton_clear)
        spacerItem2 = QtWidgets.QSpacerItem(25, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_add = QtWidgets.QPushButton(self.lower_right_frame_2)
        self.pushButton_add.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00c580;\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(38, 127, 51, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 136, 86);\n"
"}")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_3.addWidget(self.pushButton_add)
        self.verticalLayout_14.addWidget(self.lower_right_frame_2, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        spacerItem3 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.lower_right_frame)
        self.verticalLayout_2.addWidget(self.middle_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.line_bottom = QtWidgets.QFrame(self.main_frame)
        self.line_bottom.setMinimumSize(QtCore.QSize(645, 4))
        self.line_bottom.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.verticalLayout_2.addWidget(self.line_bottom, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lower_frame = QtWidgets.QFrame(self.main_frame)
        self.lower_frame.setObjectName("lower_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.lower_frame)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_delete = QtWidgets.QPushButton(self.lower_frame)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(197, 0, 3);\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(127, 38, 38, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(136, 0, 2);\n"
"}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_2.addWidget(self.pushButton_delete)
        spacerItem4 = QtWidgets.QSpacerItem(26, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton_save = QtWidgets.QPushButton(self.lower_frame)
        self.pushButton_save.setMinimumSize(QtCore.QSize(135, 40))
        self.pushButton_save.setMaximumSize(QtCore.QSize(135, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00c580;\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(38, 127, 51, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 136, 86);\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.verticalLayout_2.addWidget(self.lower_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.main_frame)
        Pass_Biom.setCentralWidget(self.centralwidget)

        self.retranslateUi(Pass_Biom)
        QtCore.QMetaObject.connectSlotsByName(Pass_Biom)

    def retranslateUi(self, Pass_Biom):
        _translate = QtCore.QCoreApplication.translate
        Pass_Biom.setWindowTitle(_translate("Pass_Biom", "Pass Biom"))
        self.label_addEdit.setText(_translate("Pass_Biom", "<html><head/><body><p><span style=\" font-weight:600;\">Додати/змінити:</span></p></body></html>"))
        self.label_lname.setText(_translate("Pass_Biom", "<html><head/><body><p>Прізвище <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_mname.setText(_translate("Pass_Biom", "<html><head/><body><p>По-батькові</p></body></html>"))
        self.label_note.setText(_translate("Pass_Biom", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span> Обов\'язкові поля</p></body></html>"))
        self.label_fname.setText(_translate("Pass_Biom", "<html><head/><body><p>Ім\'я <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_passport.setText(_translate("Pass_Biom", "<html><head/><body><p>Серія/Номер паспорта <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_post.setText(_translate("Pass_Biom", "<html><head/><body><p>Посада <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_batchAdding.setText(_translate("Pass_Biom", "<html><head/><body><p><span style=\" font-weight:600;\"> Пакетне додавання осіб</span></p></body></html>"))
        self.label_note_1.setText(_translate("Pass_Biom", "<html><head/><body><p><span style=\" font-weight:600;\">Обов\'язковий підпис зображення:</span><br/>Посада_особи ID_документа Прізвище Ім\'я По-батькові<br/><br/><span style=\" font-weight:600;\">Приклад:</span><br/>Комп\'ютерний_інженер 123456789 Мельник Марія Іванівна</p></body></html>"))
        self.pushButton_clear.setText(_translate("Pass_Biom", "Очистити"))
        self.pushButton_add.setText(_translate("Pass_Biom", "Додати"))
        self.pushButton_delete.setText(_translate("Pass_Biom", "Видалити особу"))
        self.pushButton_save.setText(_translate("Pass_Biom", "Зберегти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pass_Biom = QtWidgets.QMainWindow()
    ui = Ui_Pass_Biom()
    ui.setupUi(Pass_Biom)
    Pass_Biom.show()
    sys.exit(app.exec())
